### PR TITLE
Example

### PR DESCRIPTION
**Pull request by dwertent**

### CODE REVIEW

**Comment by HollowMan6** [comment]
You can see the code suggestion by committing something that introduces new issues that can get fixed by kubescape.

**Comment by HollowMan6** [comment]
https://github.com/kubescape/github-action/pull/33#issuecomment-1494279001

As GitHub doesn't support making reviews on a content that is not related to that specific PR.

So that's why that error exists: https://github.com/kubescape/github-action/pull/33#pullrequestreview-1368878262

**Comment by HollowMan6** [comment]
In addition, I just checked and found the error at https://github.com/kubescape/github-action/actions/runs/4596346433/jobs/8118910909 `Error: GitHub Actions is not permitted to create or approve pull requests.`

So remember to allow GitHub Actions to create and approve pull requests like https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#preventing-github-actions-from-creating-or-approving-pull-requests to get it work. But after all we don't want to see another PR gets opened unless we commit to the main branch directly.

**Comment by HollowMan6** [comment]
Examples available at my fork:

- https://github.com/HollowMan6/github-action/pull/1
- https://github.com/HollowMan6/github-action/pull/2

**Comment by dwertent** [comment]
Thanks @HollowMan6 !

**Pull request closed without merging**
