### PR TITLE
minor changes

### PR DESCRIPTION
**Pull request by dwertent**

### CODE REVIEW

**Comment by dwertent** [comment]
@HollowMan6 Can you please take a look at the failed job?

**Comment by HollowMan6** [comment]
That's interesting, I haven't tested the situation where you start a PR with its own repo, so I think we will need to restrict the branch for the push event.

Also please change it into reviewdog if you want to avoid these errors. I will start another PR to fix this.

> Some suggestions could not be made:
> 
> * examples/kubernetes-manifests/adservice.yaml
>   
>   * lines 44-43
> * examples/kubernetes-manifests/cartservice.yaml
>   
>   * lines 45-44
> * examples/kubernetes-manifests/checkoutservice.yaml
>   
>   * lines 44-43
> * examples/kubernetes-manifests/frontend.yaml
>   
>   * lines 46-45

**Comment by HollowMan6** [comment]
Fix available in #34 @dwertent

**Comment by dwertent** [comment]
I will open a new PR

**Comment by HollowMan6** [comment]
The reviewdog works by only proposing suggestions for the changes that is related to the PR, so this should be the right behavior as no suggestions have been proposed.

**Pull request closed without merging**
